import Featured from '@/components/Featured'
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import Navbar from '@/components/Navbar'
import SpecialisedTracks from '@/components/SpecialisedTracks'
import StudentTetimonial from '@/components/StudentTetimonial'
import Team from '@/components/Team'
import Head from 'next/head'
import Image from 'next/image'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Navbar/>
        <Hero></Hero>
        <Featured></Featured>
        <SpecialisedTracks></SpecialisedTracks>
        <Team></Team>
        <StudentTetimonial></StudentTetimonial>
        
        <Footer/>

      </main>
    </>
  )
}
